INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 1", "clean", 100, 100, 1);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 2", "protect", 1000, 7, 23);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 3", "defend", 200, 45, 100);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 4", "fight", 50, 32, 107);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 5", "read", 10, 11, 54);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 6", "shower", 40, 7, 75);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 7", "feed", 500, 80, 80);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 8", "water", 11100, 60, 13);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 9", "walk", 100000, 30, 1);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 10", "run", 200, 20, 3);

INSERT INTO users (name, age) VALUES ("sam", 2);
INSERT INTO users (name, age) VALUES ("tom", 21);
INSERT INTO users (name, age) VALUES ("john", 24);
INSERT INTO users (name, age) VALUES ("guy", 13);
INSERT INTO users (name, age) VALUES ("jim", 25);
INSERT INTO users (name, age) VALUES ("tony", 54);
INSERT INTO users (name, age) VALUES ("ali", 40);
INSERT INTO users (name, age) VALUES ("tom", 30);
INSERT INTO users (name, age) VALUES ("mace", 10);
INSERT INTO users (name, age) VALUES ("cray", 15);
INSERT INTO users (name, age) VALUES ("larry", 2);
INSERT INTO users (name, age) VALUES ("mo", 21);
INSERT INTO users (name, age) VALUES ("jerry", 24);
INSERT INTO users (name, age) VALUES ("phil", 13);
INSERT INTO users (name, age) VALUES ("max", 25);
INSERT INTO users (name, age) VALUES ("mendel", 54);
INSERT INTO users (name, age) VALUES ("kevin", 40);
INSERT INTO users (name, age) VALUES ("ari", 30);
INSERT INTO users (name, age) VALUES ("sammy", 10);
INSERT INTO users (name, age) VALUES ("hanna", 15);

INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 10, 10);
